#!/bin/sh

### BEGIN INIT INFO
# Provides:       mmclientd
# Required-Start: xen
# Required-Stop:  xen
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: start or stop xen memory management client daemon
### END INIT INFO

RETVAL=0
PATH="/usr/local/bin:/usr/bin:$PATH"
prog="mmclient"
export XENSTORED_PATH=/dev/xen/xenbus

start() {
    # Start daemons.
    echo -n "Starting $prog: "
    daemon mmclient $OPTIONS
    renice -10 -p `pidof mmclient` 
    RETVAL=$?
    echo
    return $RETVAL
}

stop() {
    echo -n "Shutting down $prog: "
    kill `pidof mmclient`
    RETVAL=$?
    echo
    return $RETVAL
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status mmclient
        RETVAL=$?
        ;;
    restart|reload)
        stop
        start
        RETVAL=$?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit $RETVAL
